_prefs: 
  baselayer: ''
  mapid: sharkins.69e17c44
  print: true
  saveCenter: true
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -75.8409
  - 45.5085
  - 14
description: Winter Wonderland Gatineau
format: "png8:m=h:c=64"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - contour.line
  - hillshade
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - original
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
  - parking_shelters
maxzoom: 21
minzoom: 11
name: Winter Wonderland Gatineau
source: "mapbox:///mapbox.mapbox-terrain-v2,sharkins.19wcow29,mapbox.mapbox-streets-v5,sharkins.7v0cf3ii"
styles: 
  - style.mss
  - road.mss
  - label.mss
  - poi.mss
  - nordic.mss
  - parking.mss
template: ''
